package com.example.engine.model.actions;

public enum ActionType {
    ATTACK_UP, ATTACK_DOWN, ATTACK_LEFT, ATTACK_RIGHT,
    MOVE_UP, MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT,
    PUT_ON_SETTLEMENT, RECRUIT_UNIT_SETTLERS, RECRUIT_UNIT_WARRIORS
}
